# **Multi-Channel Supply Chain Warehouse Inventory & Safety Stock Framework**

### **Objective**

**Sales Trend Analysis & Demand Forecasting**

* Identifying which product categories sell the most during specific months.
* Tracking how much promotions increase overall sales.

**Inventory Optimization & Stockouts Avoidance**

* Comparing Qty on Hand against Qty Sold to identify stores facing stockout risks or holding slow-moving inventory.
* Establishing optimal safety stock levels.

**Profitability & Business Margin Analysis**

* Measuring true business profitability by calculating net profit margins ($\text{Sales Amount} - \text{COGS}$) across different product segments.

* Identifying which stores and sales channels are performing the best financially.
* Evaluating and quantifying the financial impact of customer product returns on overall profits.

### **Dataset Information**

Source: Mendeley Data Repository.

Location:  USA Retail Market

Year/Timeline: Data collected during the period 2025 to 2026.

Domain: Retail, Supply Chain, and Inventory Management.

In [ ]:
# IMPORTING LIBRARIES

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

In [ ]:
#Loading data from Local drive

from google.colab import files
uploaded = files.upload()

Saving retail_inventory_ml_apl.csv to retail_inventory_ml_apl (1).csv
Saving retail_sales_ml_apl.csv to retail_sales_ml_apl (1).csv

In [ ]:
#csv file is converted into Data Frame using pandas

df_inventory = pd.read_csv("retail_inventory_ml_apl.csv")

df_sales = pd.read_csv("retail_sales_ml_apl.csv")

### **Initial Inspection / Initial EDA**

Inventory

In [ ]:
#Seeing the Sample

df_inventory.head()

,Start Date,End Date,Stock Status,Supplier,Product No,Product Description,Product Division,Product Category,Product Subcategory,Product Segment,Store,Store Type,Sales Channel,Qty on hand,Stocks Selling Amount,Cost of Stocks,Stock Unit Selling Price,Stock Unit Cost Price
0,07-08-2025,18-10-2025,Full Price,Vendor 0255,PROD-159369,PROD-103395 SEG-500461 Scholar Footwear Canvas...,Scholar Footwear,Scholar Footwear Canvas Styles,Scholar Footwear Canvas Styles Drifter,SEG-500461 Scholar Footwear Canvas Styles Drifter,STR-1010,Retail Storefront,Channel Alpha,1,55.0,24.75,55.0,24.75
1,15-02-2026,15-02-2026,Full Price,Vendor 0010,PROD-180713,PROD-190644 SEG-520887 Femme Footwear Court Ca...,Femme Footwear,Femme Footwear Court Casual,Femme Footwear Court Casual Trident,SEG-520887 Femme Footwear Court Casual Trident,STR-1082,Retail Storefront,Channel Alpha,1,130.0,59.73,130.0,59.73
2,08-01-2026,15-02-2026,Full Price,Vendor 0166,PROD-169474,PROD-153439 SEG-512518 Femme Footwear Court Ca...,Femme Footwear,Femme Footwear Court Casual,Femme Footwear Court Casual Zephyr,SEG-512518 Femme Footwear Court Casual Zephyr,STR-1105,Retail Storefront,Channel Alpha,1,120.0,60.44,120.0,60.44
3,23-12-2025,15-02-2026,Full Price,Vendor 0106,PROD-170976,PROD-122029 SEG-504463 Junior Apparel Cozy Pul...,Junior Apparel,Junior Apparel Cozy Pullovers,Junior Apparel Cozy Pullovers Varied,SEG-504463 Junior Apparel Cozy Pullovers Varied,STR-1157,Retail Storefront,Channel Alpha,3,150.0,52.50,50.0,17.50
4,10-02-2026,31-12-9999,Full Price,Vendor 0134,PROD-183525,PROD-111954 SEG-502325 Scholar Footwear Modern...,Scholar Footwear,Scholar Footwear Modern Legend,Scholar Footwear Modern Legend Summit,SEG-502325 Scholar Footwear Modern Legend Summit,STR-1253,Retail Storefront,Channel Alpha,4,360.0,182.16,90.0,45.54

In [ ]:
#Checking Data Structure

df_inventory.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284755 entries, 0 to 284754
Data columns (total 18 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Start Date                284755 non-null  object
 1   End Date                  284755 non-null  object
 2   Stock Status              284755 non-null  object
 3   Supplier                  284755 non-null  object
 4   Product No                284755 non-null  object
 5   Product Description       284755 non-null  object
 6   Product Division          284755 non-null  object
 7   Product Category          284755 non-null  object
 8   Product Subcategory       284755 non-null  object
 9   Product Segment           284755 non-null  object
 10  Store                     284755 non-null  object
 11  Store Type                284755 non-null  object
 12  Sales Channel             284755 non-null  object
 13  Qty on hand               284755 non-null  int64
 14  Stocks Selling Amount     284755 non-null  float64
 15  Cost of Stocks            284755 non-null  float64
 16  Stock Unit Selling Price  284755 non-null  float64
 17  Stock Unit Cost Price     284755 non-null  float64
dtypes: float64(4), int64(1), object(13)
memory usage: 39.1+ MB

In [ ]:
#Checking Column Names

df_inventory.columns

Index(['Start Date', 'End Date', 'Stock Status', 'Supplier', 'Product No',
       'Product Description', 'Product Division', 'Product Category',
       'Product Subcategory', 'Product Segment', 'Store', 'Store Type',
       'Sales Channel', 'Qty on hand', 'Stocks Selling Amount',
       'Cost of Stocks', 'Stock Unit Selling Price', 'Stock Unit Cost Price'],
      dtype='object')

In [ ]:
#Quick Math Summary

df_inventory.describe()

,Qty on hand,Stocks Selling Amount,Cost of Stocks,Stock Unit Selling Price,Stock Unit Cost Price
count,284755.000000,284755.000000,284755.000000,284755.000000,284755.000000
mean,2.294629,224.392566,111.046256,95.313171,47.419488
std,2.007395,214.479811,105.785092,46.655771,23.776569
min,-9.000000,-828.000000,-418.950000,0.000000,-16.940000
25%,1.000000,95.000000,46.430000,75.000000,37.950000
50%,2.000000,160.000000,80.960000,100.000000,50.050000
75%,3.000000,300.000000,149.170000,120.000000,60.720000
max,56.000000,5600.000000,2641.450000,250.000000,336.380000

In [ ]:
#Checking datatypes

df_inventory.dtypes

Start Date                   object
End Date                     object
Stock Status                 object
Supplier                     object
Product No                   object
Product Description          object
Product Division             object
Product Category             object
Product Subcategory          object
Product Segment              object
Store                        object
Store Type                   object
Sales Channel                object
Qty on hand                   int64
Stocks Selling Amount       float64
Cost of Stocks              float64
Stock Unit Selling Price    float64
Stock Unit Cost Price       float64
dtype: object

In [ ]:
#Finding Repeat Rows

df_inventory.duplicated().sum()

np.int64(0)

In [ ]:
#Finding Empty Cells

df_inventory.isnull().sum()

Start Date                  0
End Date                    0
Stock Status                0
Supplier                    0
Product No                  0
Product Description         0
Product Division            0
Product Category            0
Product Subcategory         0
Product Segment             0
Store                       0
Store Type                  0
Sales Channel               0
Qty on hand                 0
Stocks Selling Amount       0
Cost of Stocks              0
Stock Unit Selling Price    0
Stock Unit Cost Price       0
dtype: int64

Sales

In [ ]:
#Seeing the Sample

df_sales.head()

,Transaction Date,Sales Type,Is Return,Reason of Return,Supplier,Product No,Product Description,Product Division,Product Category,Product Subcategory,Product Segment,Store,Sales Channel,Qty Sold,Sales Amount,Cogs,Number of Transactions
0,01-09-2025,Full Price,0,NaN,Vendor 0169,PROD-139867,PROD-100449 SEG-500065 Scholar Footwear Trailb...,Scholar Footwear,Scholar Footwear Trailblazer,Scholar Footwear Trailblazer Equilibrium,SEG-500065 Scholar Footwear Trailblazer Equili...,STR-1006,Channel Alpha,1,115.00,52.31,1
1,07-09-2025,Full Price,0,NaN,Vendor 0166,PROD-100449,PROD-100825 SEG-500112 Heritage Footwear Fligh...,Femme Footwear,Femme Footwear Flight Classic,Femme Footwear Flight Classic Varied,SEG-500112 Heritage Footwear Flight Classic Ze...,STR-1198,Channel Alpha,1,115.00,58.47,1
2,06-08-2025,Promo,0,NaN,Vendor 0169,PROD-153623,PROD-148813 SEG-511388 Scholar Footwear Trailb...,Scholar Footwear,Scholar Footwear Trailblazer,Scholar Footwear Trailblazer Equilibrium,SEG-511388 Scholar Footwear Trailblazer Equili...,STR-1157,Channel Alpha,1,79.99,43.76,1
3,31-08-2025,Full Price,0,NaN,Vendor 0246,PROD-140876,PROD-100419 SEG-500063 Scholar Footwear Boot C...,Scholar Footwear,Scholar Footwear Boot Collection,Scholar Footwear Boot Collection Woodland,SEG-500063 Scholar Footwear Boot Collection Wo...,STR-1234,Channel Alpha,1,110.00,50.60,1
4,22-03-2026,Full Price,0,NaN,Vendor 0169,PROD-166113,PROD-149345 SEG-511444 Femme Footwear Trailbla...,Femme Footwear,Femme Footwear Trailblazer,Femme Footwear Trailblazer Equilibrium,SEG-511444 Femme Footwear Trailblazer Equilibrium,STR-1157,Channel Alpha,1,160.00,77.95,1

In [ ]:
#Checking Data Structure

df_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125751 entries, 0 to 125750
Data columns (total 17 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Transaction Date        125751 non-null  object
 1   Sales Type              125751 non-null  object
 2   Is Return               125751 non-null  int64
 3   Reason of Return        0 non-null       float64
 4   Supplier                125751 non-null  object
 5   Product No              125751 non-null  object
 6   Product Description     125751 non-null  object
 7   Product Division        125751 non-null  object
 8   Product Category        125751 non-null  object
 9   Product Subcategory     125751 non-null  object
 10  Product Segment         125751 non-null  object
 11  Store                   125751 non-null  object
 12  Sales Channel           125751 non-null  object
 13  Qty Sold                125751 non-null  int64
 14  Sales Amount            125751 non-null  float64
 15  Cogs                    125751 non-null  float64
 16  Number of Transactions  125751 non-null  int64
dtypes: float64(3), int64(3), object(11)
memory usage: 16.3+ MB

In [ ]:
#Checking Column Names

df_sales.columns

Index(['Transaction Date', 'Sales Type', 'Is Return', 'Reason of Return',
       'Supplier', 'Product No', 'Product Description', 'Product Division',
       'Product Category', 'Product Subcategory', 'Product Segment', 'Store',
       'Sales Channel', 'Qty Sold', 'Sales Amount', 'Cogs',
       'Number of Transactions'],
      dtype='object')

In [ ]:
#Quick Math Summary

df_sales.describe()

,Is Return,Reason of Return,Qty Sold,Sales Amount,Cogs,Number of Transactions
count,125751.00000,0.0,125751.000000,125751.000000,125751.000000,125751.000000
mean,0.05957,NaN,0.930370,83.356079,46.502621,1.042695
std,0.23669,NaN,0.586897,83.658776,43.597511,0.305832
min,0.00000,NaN,-3.000000,-380.000000,-192.280000,1.000000
25%,0.00000,NaN,1.000000,50.000000,37.710000,1.000000
50%,0.00000,NaN,1.000000,90.000000,50.050000,1.000000
75%,0.00000,NaN,1.000000,115.000000,60.720000,1.000000
max,1.00000,NaN,14.000000,2660.000000,1345.960000,14.000000

In [ ]:
#Checking datatypes

df_sales.dtypes

Transaction Date           object
Sales Type                 object
Is Return                   int64
Reason of Return          float64
Supplier                   object
Product No                 object
Product Description        object
Product Division           object
Product Category           object
Product Subcategory        object
Product Segment            object
Store                      object
Sales Channel              object
Qty Sold                    int64
Sales Amount              float64
Cogs                      float64
Number of Transactions      int64
dtype: object

In [ ]:
#Finding Repeat Rows

df_sales.duplicated().sum()

np.int64(0)

In [ ]:
#Finding Empty Cells

df_sales.isnull().sum()

Transaction Date               0
Sales Type                     0
Is Return                      0
Reason of Return          125751
Supplier                       0
Product No                     0
Product Description            0
Product Division               0
Product Category               0
Product Subcategory            0
Product Segment                0
Store                          0
Sales Channel                  0
Qty Sold                       0
Sales Amount                   0
Cogs                           0
Number of Transactions         0
dtype: int64